version: '3.1'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: foospoll
      POSTGRES_PASSWORD: foospoll
      POSTGRES_DB: foospoll
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  bot:
    build: .
    volumes:
      - photostorage:/opt/photostorage
    depends_on:
      - postgres
    ports:
      - 8899:8899
volumes:
  postgresdata:
  photostorage:
